### ISSUE TITLE
ios下面无法升级下载

### ISSUE THREAD

**Issue by zpinsist** [SunSeekerX/uni-pushy-server#5]
ios版的wgt更新，是需要什么特别的权限或者一定要打正式包才能更新下载吗，我直接用的hbx调试基座打的包，在ios下面并不能直接更新下载。 
[![6gyASO.md.jpg](https://s3.ax1x.com/2021/03/18/6gyASO.md.jpg)](https://imgtu.com/i/6gyASO)
[![6gyFfK.md.jpg](https://s3.ax1x.com/2021/03/18/6gyFfK.md.jpg)](https://imgtu.com/i/6gyFfK)

**Comment by SunSeekerX** [comment]
管理平台并没有 ios 的 wgt 的资源包，所以是无法下载更新的。。

![image](https://user-images.githubusercontent.com/48562733/111599311-1d265000-880b-11eb-98b0-c8701425c2f1.png)

**Comment by zpinsist** [comment]
> 管理平台并没有 ios 的 wgt 的资源包，所以是无法下载更新的。。
> 
> ![image](https://user-images.githubusercontent.com/48562733/111599311-1d265000-880b-11eb-98b0-c8701425c2f1.png)

我自己创建了一个帐号，项目id是5fb06b7806d91c23c179abdb7706704c，我在里面上传了wgt包。

**Comment by SunSeekerX** [comment]
> t

你加我一下 Q:1647800606
